version: 2.1

parameters:
  is_rollback:
    type: boolean
    default: false
    
workflows:
  rollback:
    when: << pipeline.parameters.is_rollback >>
    jobs:
      - trigger_rollback
jobs:
  trigger_rollback:
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          command: |
            echo "Rolling back changes to previous state..."
