version: 2.1
jobs:
  rollback:
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          command: |
            echo "Rolling back changes to previous state..."
workflows:
  build:
    jobs:
      - rollback
